// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANNACNOKwe_2WRqJi1dzFS7tML3SkjqoE',
    appId: '1:294481322328:web:2d31b70063d3a6730a052d',
    messagingSenderId: '294481322328',
    projectId: 'fluttergram-f438d',
    authDomain: 'fluttergram-f438d.firebaseapp.com',
    storageBucket: 'fluttergram-f438d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBEGA_vzG5ObhwmzGmJk_hfE6NQacPqdE',
    appId: '1:294481322328:android:be28620e0589ee3a0a052d',
    messagingSenderId: '294481322328',
    projectId: 'fluttergram-f438d',
    storageBucket: 'fluttergram-f438d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7AsZFHvJJ6THmyEOO458N3J32g9d8A_U',
    appId: '1:294481322328:ios:2e11efbf36b47e9e0a052d',
    messagingSenderId: '294481322328',
    projectId: 'fluttergram-f438d',
    storageBucket: 'fluttergram-f438d.appspot.com',
    iosBundleId: 'com.parkjh.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7AsZFHvJJ6THmyEOO458N3J32g9d8A_U',
    appId: '1:294481322328:ios:2e11efbf36b47e9e0a052d',
    messagingSenderId: '294481322328',
    projectId: 'fluttergram-f438d',
    storageBucket: 'fluttergram-f438d.appspot.com',
    iosBundleId: 'com.parkjh.instagram',
  );
}
